#!/usr/bin/env bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

set -eu

cd "$DIR"

ansible-vault \
  encrypt_string \
  --vault-id prod@~/.config/cygnus/vault-password \
  --name="$1"
