#!/usr/bin/env bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

set -eu

target_host="$1"

cd "$DIR"

tar --strip-components=1 -cf fs.tar root

set -x

# start the ssh session
ssh -f -N -M -o "ControlPath=./ssh.sock" -o "ControlPersist=10m" "$target_host"

# push fs to remote machine
scp -o "ControlPath=./ssh.sock" ./fs.tar "${target_host}:/tmp/fs.tar"

# unpack the fs
ssh -o "ControlPath=./ssh.sock" "$target_host" "sudo tar -xf /tmp/fs.tar -C /"

# run the apply script
ssh -o "ControlPath=./ssh.sock" "$target_host" "sudo /usr/local/cygnus/apply"

# finish ssh session
ssh -O stop -o "ControlPath=./ssh.sock" "$target_host"
