debug = true

[entryPoints.web]
  address = ":80"
# TODO: bring it back, when cert-manager is in place
#   [entryPoints.web.http.redirections.entryPoint]
#     to = "websecure"
#     scheme = "https"

[entryPoints.websecure]
  address = ":443"

[entryPoints.kubeapi]
  address = ":6443"

[certificatesResolvers.cloudflare.acme]
  email = "liam@ldaws.com"
  keyType = "EC384"
  storage = "/etc/traefik/acme.json"

  [certificatesResolvers.cloudflare.acme.dnsChallenge]
    provider = "cloudflare"
    delayBeforeCheck = 5

[providers]
file = { filename = "/etc/traefik/static.yaml" }
# configured via traefik + traefik-external systemd services
kubernetesIngress = {}

# TODO: secure or remove
[api]
  dashboard = true
  insecure = true
