#!/usr/bin/env sh

# hacky way to ensure the route exists for Traefik's ingresses
# designed to run through sirius, so polaris should still be accessible
# during a routed network flood... maybe?

if [ "$1" = "sirius" ]; then
  if [ "$2" = "stopped" ] || [ "$2" = "reconnect" ]; then
    ip route del 10.42.0.0/16 dev brkubenet via 192.168.53.10 || [ "$?" = "2" ]
  fi

  if [ "$2" = "start" ] || [ "$2" = "reconnect" ]; then
    ip route add 10.42.0.0/16 dev brkubenet via 192.168.53.10
  fi
fi
