#!/usr/bin/env bash

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd)"
dest="cache/debian-10.4.0-amd64-xfce-CD-1.iso"

cd "$DIR"

iso_urls=(
  http://mirror.aarnet.edu.au/pub/debian-cd/10.4.0/amd64/iso-cd/debian-10.4.0-amd64-xfce-CD-1.iso
  https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-10.4.0-amd64-xfce-CD-1.iso
)

for u in "${iso_urls[@]}"; do
  echo "Trying ${u}"
  curl -fLo "$dest" "$u" && exit 0
done

exit 1
