#!/usr/bin/env bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

set -eu

cd "$DIR"

set -x

# dependencies
apt-get install -y \
  curl \
  libosinfo-bin \
  virtinst

# traefik config
chmod 0775 /etc/traefik
chown -R traefik:traefik /etc/traefik
chmod 0640 /etc/traefik/{traefik-cloudflare-api-token,acme.json}

systemctl enable traefik

# libvirt config
virsh net-info kubenet >/dev/null 2>&1 \
  || virsh net-define /usr/local/cygnus/libvirt/kubenet.xml

virsh pool-info default >/dev/null 2>&1 \
  || virsh pool-define /usr/local/cygnus/libvirt/default-pool.xml

usermod liamdawson -aG libvirt

# apply configuration updates last
systemctl restart traefik
