#!/usr/bin/env bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

set -eu

target_hostname="$1"
mac_address="$2"

kernel_args="\
k3os.k3s_args=server \
"

cd "$DIR"

./_mk-kube-virt "$kernel_args" 2048 "$target_hostname" "$mac_address"
