#!/usr/bin/env bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

set -eu

target_hostname="$1"
mac_address="$2"
node_token="$3"

kernel_args="\
k3os.k3s_args=agent \
k3os.token=${node_token} \
"

cd "$DIR"

./_mk-kube-virt "$kernel_args" 6144 "$target_hostname" "$mac_address"
